Resources:
    InstanceSecurityGroup:
        Type: 'AWS::EC2::SecurityGroup'
        Properties:
            GroupDescription: Enable SSH access via port 22
            SecurityGroupIngress:
              - IpProtocol: tcp
                FromPort: '22'
                ToPort: '22'
                CidrIp: 0.0.0.0/0
    WebInstance:
        Type: 'AWS::EC2::Instance'
        Properties:
            InstanceType: t2.nano
            SecurityGroups:
              - !Ref InstanceSecurityGroup
            KeyName: ubuntu
            ImageId: 'ami-0516faeafaf906b64' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
    