version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - add_ssh_key:
          fingerprints: ["d7:7d:14:bd:58:b5:59:78:1e:95:67:31:71:d1:f2:b5:a4:c1:34:e4"]
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name my-stack \
              --region=eu-west-3
workflows:
  my_workflow:
    jobs:
      - create_infrastructure